<?php

function cars_custom_node_presave($node) { 
  /* if($node->type == 'cars'){
    $betititle = $node->field_year['und'][0]['value'];
    $betititle = $betititle.' '.$node->field_make['und'][0]['value'];
    $betititle = $betititle.' '.$node->field_model['und'][0]['value'];
    $betititle = $betititle.' '.$node->field_trim['und'][0]['value'];
    $node->title = $betititle;
  } */
}
function cars_custom_feeds_after_parse(FeedsSource $source, FeedsParserResult $result) {
  /* if ($source->id == 'cars_importer2') {
    dpm($result->items);
    foreach ($result->items as &$item) {
      // Уменьшаем длину поля my_data_item
      $item['my_data_item'] = drupal_substr($item['my_data_item'], 0, 32);
    }
  } */
}